spring:
    application:
        name: user-service
    docker:
      compose:
        file: "../../compose.yaml"
    datasource:
        url: jdbc:postgresql://localhost:5432/user_db
        username: postgres
        password: password
#         driver-class-name: org.postgresql.Driver
#     jpa:
#         hibernate:
#             ddl-auto: update
#         show-sql: false
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.PostgreSQLDialect
#                 format_sql: true

server:
    port: 8082

jwt:
    secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBkZXZlbG9wbWVudA==

management:
    endpoints:
        web:
            exposure:
                include: health,prometheus
    endpoint:
        health:
            probes:
                enabled: true
