spring:
    main:
        banner-mode: off
    application:
        name: api-gateway

services:
    auth-service:
        url: http://localhost:8081
    user-service:
        url: http://localhost:8082

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: health,prometheus
    endpoint:
        health:
            probes:
                enabled: true

logging:
    level:
        root: WARN