apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - auth-service-monitor.yaml
    - user-service-monitor.yaml
    - api-gateway-monitor.yaml
    - crate-service-monitor.yaml
    - sync-service-monitor.yaml
