apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: sync-service
    labels:
        app: sync-service
spec:
    namespaceSelector:
        matchNames:
            - jv-eks
    selector:
        matchLabels:
            app: sync-service
    endpoints:
        - port: http
          path: /actuator/prometheus
          interval: 30s
          scrapeTimeout: 10s
