apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: user-service
    labels:
        app: user-service
spec:
    namespaceSelector:
        matchNames:
            - jv-eks
    selector:
        matchLabels:
            app: user-service
    endpoints:
        - port: http
          path: /actuator/prometheus
          interval: 30s
          scrapeTimeout: 10s
