apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-service-config
data:
    SPRING_APPLICATION_NAME: auth-service
    SERVER_PORT: '8081'
    SPRING_DOCKER_COMPOSE_ENABLED: 'false'
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: 'true'
    # Overridden per environment in overlays
    SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/auth_db
    SPRING_DATASOURCE_USERNAME: postgres
