apiVersion: v1
kind: ConfigMap
metadata:
    name: sync-service-config
data:
    SPRING_APPLICATION_NAME: sync-service
    SERVER_PORT: '8084'
    SPRING_DOCKER_COMPOSE_ENABLED: 'false'
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: 'true'
    # Overridden per environment in overlays
    SPRING_DATA_REDIS_HOST: localhost
    SPRING_DATA_REDIS_PORT: '6379'
