apiVersion: v1
kind: ConfigMap
metadata:
    name: api-gateway-config
data:
    SPRING_APPLICATION_NAME: api-gateway
    SERVER_PORT: '8080'
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: 'true'
    # In-cluster DNS — auth-service and user-service K8s Service names
    SERVICES_AUTH_SERVICE_URL: http://auth-service:8081
    SERVICES_USER_SERVICE_URL: http://user-service:8082
