---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: jv-eks
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCRyOjHSqjlbtZSCkMz9aR/tKZa3SBK26V6Fm7PMA7xfzmUK0UCMia1pHYkzJlDIlaZejMGbeqqIGqxei8SAoE3IpfOPslKz+GGelNXyhGmDqhRoU4boVbs5yzN0wb9CdPBvU8uP+Y1037uytskrAtCgzFiquAm5jro3+zc68Bjdbp+baTfQOhaCt1LEP5hFMvDCHbCY0EweaY9f78XmFYmDNjghaDI71xGeclxFFifdvDlYoTKsaMbeGLmUpYgdFfvyB7rz2ZRzVh6FjEmsLb9k2EnvEoZWxbAwwZiML9M3fghw9EXRQaVIIw7GooUrWQsczy4KCq3Ht4FCII07kNZFVQb1FinFsqlVNqA1TM03zqTfESag+4dd1ac1lY3iK+w2B8ZL122p/9uTryWbwzYQ/6Sv8yfi9s0BAIM1wojt/Mt1gV6hg0se1ybjjcfiXA41K1nf79/tmjI9XGUUlqMSe0e8Fn+20HQ3tG1wzoa5H0B8z4Syma88FAweK7SY+f9+nH3vQ94i+jNPzQu6lIcvmfnHF9ik4J7FiLmPmtSJ5KnJkg14yoMYoUxoGMzl6cF5rx5KLwWXrmeBBGLDYRPIMssy+zB51vy1lrjx8g1T++KlK+00EHAZxRulNxvpTDA/cM1rXOPxmsBzeKLLqZyZyir5XJoxb9JHN3EGGROyaeQ/Qbd4lgDd+a3MYmhHZuo7HAtF/E+ng==
  template:
    metadata:
      name: db-secret
      namespace: jv-eks
