---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: jv-eks
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBu5BCNsmaeRoBgK6YoOzpUx6g+Ti4o5+yk3uyuxs8BcoCyHLH6B/GQgM7HFHDFd4GJYSjVpQsHHRWAEzmII5Ogw2DjWLh7dNd17vUQmC1rRTPCxd7fH+tdUIS+kqcyBvBS0UTCdeA+iBPk/eSTm6R7GrI+/kmcKNLfFeKMQ/gnrfv7NWxiT2vS7Fq0uzCTdy9wmHzqffYyj+k8tDJt3E1ZYVYiqJxqyB281LXj8MFqBQjjsHj4dA+jLynEhb7G4c/+/nTJrir5ymCzbZWNp2NdnRqO/LaqWpqpZps780p0Z+2jgXjtlEe4qWS3mf52AaOSfPbChiFqBoPicUjj9bxUGMiL+IlWQ5UAMAB0aKNECywEPS3O3csGX+2wx6gmLl5OtnYDTaEQlk0hN9qh1jqrVAGZTiKWiFNFnpNCf8aDxUlgV/+d0pD6XBoPi80xNz1pSjYUjSgAdYUaRzDzO9TWosSAJdbo4FbJesDerammQ96otQH0AIRVrQmBRI0Apvjp23dNbElhpP7CQQLNrGzWCn/ECwcAtakUR+AhiEvUc9B3LJ0y0SWbLhnAnltkApiifYO8AnYmvCcqgo1U4boAUiuHAVSeb19giiuLDq4SqJ3e2zDqCywktmKflXJGplvny/lF93r5ertXogy4kV82AjGdqjTszcgA//ChSnb8/x6rXy0v0ToSoTwv8xahlfpmL4yh1j8L+A==
  template:
    metadata:
      name: db-secret
      namespace: jv-eks
