---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: jv-eks
spec:
  encryptedData:
    JWT_SECRET: AgCB+veoCdPLGnkPLo/Wfc3wphnQGmU7cAy0DaBkd9hFVJsYwERhPLi5C3szfdMdoK0gJlZNdgD4UnW5vUzssp7dhkPFw6N2VKzGYqW1OLncc2s4Nv0O69uBhaE3svsbGv0cM5MaMfG9noqij+ivWvzrw6lvHsz7x2y/fKzznjXqZq2UpRBA9CyfMdNJhPrZPmMaoMTRa0vchAfzWBCYShpqi8lfC5hHVg/c42SiDJ+gm5/qN25P01MGi3GnsO0xD6kJkbZ4ZA2f3Hbfs212S6+js6j9axwoQONVQf6wKwRvgx2DeShcdetVmQbpE4Yye6w4qrljjFM562Y7I9gJnwm8ZrhM4DwQmobRCtX1oFYVE0lKslYPEOy+vUZD0/kCj58QMP2GoYnUOLdXvwDg1sW9RZt2eocatr1qmO6HBZr2WcShAlDu79BXpFGFGGewMprq5ZGp2JJ+0CxNw/mFGeLmkCggeUS5/U7LjhSf8Lt016CE19EWGXxsGUAS7wBpOwph8Ti8JBP7yxx9xcwrm8DlXx1wVV5+vknW92LzVAUIliNV3emg3uO8ReT3YCZy1A0wAvY4JPvaLKJ1Z6kEWOKZjOBR839kAiGrL0PNalmL6qYis4iHIHhx8+4007+9Y/QqFmt91vsQ1cy+NMHWYfz4llbbcRn1AP4TCn28i4WHDtYMsxvz4u65ciUsNUkuy1IXcyBDSmtMiRZJ5INWvZZgUFw5Ffgu7rHM6SDgNpZ3/X0DecjeaSprFpbA5T0VqoXkopKOg0ipPivY0F7Dvx5l
  template:
    metadata:
      name: jwt-secret
      namespace: jv-eks
