---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: jv-eks
spec:
  encryptedData:
    JWT_SECRET: AgDc6cGZaQ7uuMnAG8NlTHUGi5zBuXcY1p/j/cuPezeREfDvfwt4syvrXqXjq0U9S5DRoUYl7AZZz8665BAqkR2Vq3Y7vv+Tv/mkBeXBcSBm8MM+pB4C07u64bkqkPmxfvyTshI1eW0CQAWN22Y49KLMLB1QTejQnQvaxF2mP30EfWiZccqybv/rbJGmt7z/5JfU/jQBKRIq1GesathDIHiQT5uvuGPf9DbCzGWvhnOV7Bdtvgul/9mKEDWXNwnfeZShqa9IzZidvUFyf+0syHDxPDIoTomb17xWnnLONVuPVOWxBp7IfZVtxkrQCTWEZU97PbIERpxDE7MJgXLjMfcT6QZDG92p9dEzz2nUSVjy3KsfO0oPnv9kqNeolXPMUAHpePk5VMwSWIyBOJZfn/3icWum49ZV/agQDkaMsTVU1QwxxWGQbK0RllYUhHaAnVvSI8Pr5IYgkgfmkgDe00fKRkMUqaOWxAHehhm1kckr3tV3qlVG9h9fDqzQeXrCO6/vPvOYS21T1ZEPNDjK+9xH84SupkuhUE1v1Y9jVhcC2YGy7jY0T92jpX7UtvxpprP3PU5ZIRoLBhYggBto4O8LLk+PkHNqww0OLVMq6rpMuz49mWwW6aS4+s9f/7tA23KqJiSlm09jaNqn+YU/FyLfBfVu7mppqizFhY7YTv63NEo12xIo/bChhmwVJMt+NIx+vpYU3RlcoPghTdWGpKxEC9VDq/TpJ12n5pZLxLT34mlnBJf5t8zYaj8FG+8LqExQZyFkXepSD70qbOcp7O2I
  template:
    metadata:
      name: jwt-secret
      namespace: jv-eks
