apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jv-eks

resources:
    - namespace.yaml
    - auth-service/
    - user-service/
    - api-gateway/
    - crate-service/
    - sync-service/
    - monitoring/
