apiVersion: v1
kind: Service
metadata:
    name: crate-service
    labels:
        app: crate-service
spec:
    selector:
        app: crate-service
    ports:
        - name: http
          port: 8083
          targetPort: 8083
    type: ClusterIP
